# Generated by Django 5.2.10 on 2026-01-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_product_alter_category_id_alter_sale_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipt',
            new_name='Receipt',
        ),
        migrations.RenameField(
            model_name='receiptitem',
            old_name='recipt',
            new_name='receipt',
        ),
    ]
