# Generated by Django 5.2.10 on 2026-01-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_recipt_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de procesar'), ('processing', 'Procesando'), ('needs_validation', 'Requiere validación'), ('validated', 'Validado'), ('completed', 'Completado'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
