# Generated by Django 5.2.10 on 2026-01-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_receipt_processed_at_receipt_status_receipt_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario del producto', max_digits=10),
        ),
    ]
