# Generated by Django 5.2.10 on 2026-01-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_sale_options_rename_amount_sale_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10),
        ),
    ]
