# Generated by Django 5.2.10 on 2026-01-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio del producto al momento de la validación', max_digits=10, null=True),
        ),
    ]
